// packages/ui/output/react/src/Loading/Loading.tsx
import * as React from "react";

export interface LoadingProps {
  size?: "sm" | "md" | "lg";
  label?: string;
  className?: string;
}

function Loading(props: LoadingProps) {
  props = { size: "md", label: "Loading...", className: "", ...props };
  return (
    <div
      role="status"
      className={`loading loading--${props.size} ${props.className}`}
      aria-label={props.label}
    >
      <span className="loading__spinner" />
      <span className="loading__label">{props.label}</span>
    </div>
  );
}

export default Loading;

// packages/ui/output/svelte/src/Loading/Loading.svelte
<script context="module" lang="ts">
  export interface LoadingProps {
    size?: "sm" | "md" | "lg";
    label?: string;
    className?: string;
  }
</script>

<script lang="ts">
  export let size: LoadingProps["size"] = "md";
  export let className: LoadingProps["className"] = "";
  export let label: LoadingProps["label"] = "Loading...";
</script>

<div
  role="status"
  class={`loading loading--${size} ${className}`}
  aria-label={label}
>
  <span class="loading__spinner" /><span class="loading__label">{label}</span>
</div>
