// packages/ui/output/react/src/ChannelListItem/ChannelListItem.tsx
"use client";
import * as React from "react";

export interface ChannelListItemProps {
  name?: string;
  unreadCount?: number;
  isActive?: boolean;
  className?: string;
  onClick?: () => void;
}

function ChannelListItem(props: ChannelListItemProps) {
  props = {
    name: "",
    unreadCount: 0,
    isActive: false,
    className: "",
    ...props,
  };
  return (
    <button
      type="button"
      className={`channel-list-item ${
        props.isActive ? "channel-list-item--active" : ""
      } ${props.className}`}
      onClick={(event) => props.onClick?.()}
    >
      <span className="channel-list-item__prefix">#</span>
      <span className="channel-list-item__name">{props.name}</span>
      <span className="channel-list-item__badge">{props.unreadCount}</span>
    </button>
  );
}

export default ChannelListItem;

// packages/ui/output/svelte/src/ChannelListItem/ChannelListItem.svelte
<script context="module" lang="ts">
  export interface ChannelListItemProps {
    name?: string;
    unreadCount?: number;
    isActive?: boolean;
    className?: string;
    onClick?: () => void;
  }
</script>

<script lang="ts">
  export let isActive: ChannelListItemProps["isActive"] = false;
  export let className: ChannelListItemProps["className"] = "";
  export let onClick: ChannelListItemProps["onClick"] = undefined;
  export let name: ChannelListItemProps["name"] = "";
  export let unreadCount: ChannelListItemProps["unreadCount"] = 0;
</script>

<button
  type="button"
  class={`channel-list-item ${
    isActive ? "channel-list-item--active" : ""
  } ${className}`}
  on:click={(event) => {
    onClick?.();
  }}
  ><span class="channel-list-item__prefix">#</span><span
    class="channel-list-item__name">{name}</span
  ><span class="channel-list-item__badge">{unreadCount}</span></button
>
