// packages/ui/output/react/src/ServerListItem/ServerListItem.tsx
"use client";
import * as React from "react";

export interface ServerListItemProps {
    avatarUrl?: string;
    className?: string;
    isActive?: boolean;
    name?: string;
    onClick?: () => void;
}

function ServerListItem(props: ServerListItemProps) {
    props = {
        avatarUrl: "",
        className: "",
        isActive: false,
        name: "",
        ...props,
    };
    return (
        <button
            type="button"
            className={`server-list-item ${
                props.isActive ? "server-list-item--active" : ""
            } ${props.className}`}
            onClick={(event) => props.onClick?.()}
            title={props.name}
        >
            <img
                className="server-list-item__avatar"
                alt={props.name}
                onError={(e) => {
                    e.currentTarget.style.display = "none";
                }}
                src={props.avatarUrl}
            />
            <span className="server-list-item__initial">
                {props.name ? (
                    <>{props.name[0]}</>
                ) : (
                    <>
                        <div _text="" />
                    </>
                )}
            </span>
        </button>
    );
}

export default ServerListItem;

// packages/ui/output/svelte/src/ServerListItem/ServerListItem.svelte
<script context="module" lang="ts">
  export interface ServerListItemProps {
    avatarUrl?: string;
    className?: string;
    isActive?: boolean;
    name?: string;
    onClick?: () => void;
  }
</script>

<script lang="ts">
  export let isActive: ServerListItemProps["isActive"] = false;
  export let className: ServerListItemProps["className"] = "";
  export let onClick: ServerListItemProps["onClick"] = undefined;
  export let name: ServerListItemProps["name"] = "";
  export let avatarUrl: ServerListItemProps["avatarUrl"] = "";
</script>

<button
  type="button"
  class={`server-list-item ${
    isActive ? "server-list-item--active" : ""
  } ${className}`}
  on:click={(event) => {
    onClick?.();
  }}
  title={name}
  ><img
    class="server-list-item__avatar"
    alt={name}
    on:error={(e) => {
      e.currentTarget.style.display = "none";
    }}
    src={avatarUrl}
  /><span class="server-list-item__initial">
    {#if name}
      {name[0]}
    {:else}
      <div _text="" />
    {/if}</span
  ></button
>
