// packages/ui/output/react/src/Avatar/Avatar.tsx
"use client";
import * as React from "react";
import { useState } from "react";

export interface AvatarProps {
    alt?: string;
    className?: string;
    displayName?: string;
    size?: "lg" | "md" | "sm" | "xs" | number;
    src?: string;
    userID?: string;
}

function Avatar(props: AvatarProps) {
    props = { alt: "", className: "", size: "md", ...props };
    function fallbackBg() {
        const id = props.userID;
        if (!id) return "hsl(0, 0%, 40%)";
        let h = 0;
        for (let i = 0; i < id.length; i++) h = (h * 31 + id.charCodeAt(i)) | 0;
        return `hsl(${Math.abs(h) % 360}, 45%, 40%)`;
    }

    function handleError() {
        setImgFailed(true);
    }

    const [imgFailed, setImgFailed] = useState(() => false);

    function initials() {
        if (props.displayName)
            return props.displayName.slice(0, 2).toUpperCase();
        if (props.userID) return props.userID.slice(0, 2).toUpperCase();
        return "?";
    }

    function px() {
        const s = props.size;
        if (typeof s === "number") return s;
        if (s === "xs") return 20;
        if (s === "sm") return 28;
        if (s === "lg") return 48;
        return 36;
    }

    return (
        <div
            className={`avatar ${props.className}`}
            style={{
                borderRadius: "50%",
                display: "inline-flex",
                flexShrink: "0",
                height: `${px()}px`,
                overflow: "hidden",
                width: `${px()}px`,
            }}
        >
            {props.src && !imgFailed ? (
                <img
                    className="avatar__img"
                    alt={props.alt}
                    height={px()}
                    onError={(event) => {
                        handleError();
                    }}
                    src={props.src}
                    style={{
                        borderRadius: "50%",
                        height: "100%",
                        objectFit: "cover",
                        width: "100%",
                    }}
                    width={px()}
                />
            ) : (
                <div
                    className="avatar__fallback"
                    style={{
                        alignItems: "center",
                        background: fallbackBg(),
                        borderRadius: "50%",
                        color: "#fff",
                        display: "flex",
                        fontSize: `${Math.round(px() * 0.4)}px`,
                        fontWeight: "700",
                        height: "100%",
                        justifyContent: "center",
                        letterSpacing: "0.02em",
                        userSelect: "none",
                        width: "100%",
                    }}
                >
                    {initials()}
                </div>
            )}
        </div>
    );
}

export default Avatar;

// apps/desktop/src/lib/Avatar.svelte
<script lang="ts">
  interface Props {
    userID: string
    serverUrl: string
    /** Cache-bust version — increment after upload to force reload */
    version?: number
    size?: number
    /** Display name or username for initials fallback */
    name?: string
  }

  let { userID, serverUrl, version = 0, size = 32, name }: Props = $props()

  let failed = $state(false)

  // Re-attempt image load whenever version changes (after upload)
  $effect(() => {
    // eslint-disable-next-line @typescript-eslint/no-unused-expressions
    version
    failed = false
  })

  function initials(id: string, displayName?: string): string {
    if (displayName) return displayName.slice(0, 2).toUpperCase()
    return id.slice(0, 2).toUpperCase()
  }

  // Deterministic hue from userID string
  function hue(id: string): number {
    let h = 0
    for (let i = 0; i < id.length; i++) h = (h * 31 + id.charCodeAt(i)) & 0xffffffff
    return Math.abs(h) % 360
  }
</script>

{#if !failed}
  <img
    src="{serverUrl}/avatar/{userID}?v={version}"
    alt={name ?? userID}
    width={size}
    height={size}
    class="avatar"
    style="width:{size}px;height:{size}px;border-radius:50%"
    onerror={() => { failed = true }}
  />
{:else}
  <div
    class="avatar avatar--fallback"
    style="width:{size}px;height:{size}px;font-size:{Math.round(size * 0.4)}px;background:hsl({hue(userID)},45%,40%)"
    aria-label={name ?? userID}
  >
    {initials(userID, name)}
  </div>
{/if}

<style>
  .avatar {
    border-radius: 50%;
    object-fit: cover;
    flex-shrink: 0;
    display: inline-flex;
  }

  .avatar--fallback {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    color: #fff;
    font-weight: 700;
    letter-spacing: 0.02em;
    user-select: none;
  }
</style>
