// packages/ui/output/svelte/src/TextInput/TextInput.svelte
<script context="module" lang="ts">
  export interface TextInputProps {
    value?: string;
    placeholder?: string;
    type?: "text" | "password" | "email" | "search";
    label?: string;
    disabled?: boolean;
    className?: string;
    onInput?: (value: string) => void;
    onChange?: (value: string) => void;
  }
</script>

<script lang="ts">
  export let className: TextInputProps["className"] = "";
  export let label: TextInputProps["label"] = "";
  export let type: TextInputProps["type"] = "text";
  export let value: TextInputProps["value"] = "";
  export let placeholder: TextInputProps["placeholder"] = "";
  export let disabled: TextInputProps["disabled"] = false;
  export let onInput: TextInputProps["onInput"] = undefined;
  export let onChange: TextInputProps["onChange"] = undefined;
</script>

<div class={`text-input ${className}`}>
  <label class="text-input__label">{label}</label><input
    class="text-input__field"
    {type}
    {value}
    {placeholder}
    {disabled}
    on:input={(e) => {
      onInput?.(e.target.value);
    }}
    on:change={(e) => {
      onChange?.(e.target.value);
    }}
  />
</div>

// packages/ui/output/react/src/TextInput/TextInput.tsx
"use client";
import * as React from "react";

export interface TextInputProps {
  value?: string;
  placeholder?: string;
  type?: "text" | "password" | "email" | "search";
  label?: string;
  disabled?: boolean;
  className?: string;
  onInput?: (value: string) => void;
  onChange?: (value: string) => void;
}

function TextInput(props: TextInputProps) {
  props = {
    value: "",
    placeholder: "",
    type: "text",
    label: "",
    disabled: false,
    className: "",
    ...props,
  };
  return (
    <div className={`text-input ${props.className}`}>
      <label className="text-input__label">{props.label}</label>
      <input
        className="text-input__field"
        type={props.type}
        value={props.value}
        placeholder={props.placeholder}
        disabled={props.disabled}
        onInput={(e) => props.onInput?.(e.target.value)}
        onChange={(e) => props.onChange?.(e.target.value)}
      />
    </div>
  );
}

export default TextInput;
