// packages/ui/output/react/src/MemberListItem/MemberListItem.tsx
import * as React from "react";

export interface MemberListItemProps {
    avatarSrc?: string;
    className?: string;
    status?: StatusDotStatus;
    userID: string;
    username?: string;
}

import type { StatusDotStatus } from "../StatusDot/StatusDot";
import Avatar from "../Avatar/Avatar";
import StatusDot from "../StatusDot/StatusDot";

function MemberListItem(props: MemberListItemProps) {
    props = {
        className: "",
        status: "offline",
        userID: "",
        username: "",
        ...props,
    };
    return (
        <div
            className={`member-list-item ${props.className}`}
            style={{
                alignItems: "center",
                borderRadius: "4px",
                display: "flex",
                gap: "8px",
                padding: "4px 8px",
            }}
        >
            <Avatar
                displayName={props.username}
                size={24}
                src={props.avatarSrc}
                userID={props.userID}
            />
            <StatusDot status={props.status} />
            <span
                className="member-list-item__name"
                style={{
                    fontSize: "13px",
                    overflow: "hidden",
                    textOverflow: "ellipsis",
                    whiteSpace: "nowrap",
                }}
            >
                {props.username || props.userID}
            </span>
        </div>
    );
}

export default MemberListItem;

// packages/ui/output/svelte/src/MemberListItem/MemberListItem.svelte
<script context="module" lang="ts">
  export interface MemberListItemProps {
    userID: string;
    username?: string;
    avatarSrc?: string;
    status?: StatusDotStatus;
    className?: string;
  }
</script>

<script lang="ts">
  import Avatar from "../Avatar/Avatar.svelte";
  import StatusDot from "../StatusDot/StatusDot.svelte";
  import type { StatusDotStatus } from "../StatusDot/StatusDot.svelte";

  export let className: MemberListItemProps["className"] = "";
  export let userID: MemberListItemProps["userID"];
  export let avatarSrc: MemberListItemProps["avatarSrc"] = undefined;
  export let username: MemberListItemProps["username"] = "";
  export let status: MemberListItemProps["status"] = "offline";
  function stringifyStyles(stylesObj) {
    let styles = "";
    for (let key in stylesObj) {
      const dashedKey = key.replace(/[A-Z]/g, function (match) {
        return "-" + match.toLowerCase();
      });
      styles += dashedKey + ":" + stylesObj[key] + ";";
    }
    return styles;
  }
</script>

<div
  style={stringifyStyles({
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "4px 8px",
    borderRadius: "4px",
  })}
  class={`member-list-item ${className}`}
>
  <Avatar {userID} src={avatarSrc} size={24} displayName={username} /><StatusDot
    {status}
  /><span
    style={stringifyStyles({
      fontSize: "13px",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    })}
    class="member-list-item__name">{username || userID}</span
  >
</div>
