// packages/ui/output/svelte/src/MessageBubble/MessageBubble.svelte
<script context="module" lang="ts">
  export interface MessageBubbleProps {
    author?: string;
    content?: string;
    timestamp?: string;
    isOwn?: boolean;
    className?: string;
  }
</script>

<script lang="ts">
  export let isOwn: MessageBubbleProps["isOwn"] = false;
  export let className: MessageBubbleProps["className"] = "";
  export let author: MessageBubbleProps["author"] = "";
  export let content: MessageBubbleProps["content"] = "";
  export let timestamp: MessageBubbleProps["timestamp"] = "";
</script>

<div
  class={`message-bubble ${isOwn ? "message-bubble--own" : ""} ${className}`}
>
  <span class="message-bubble__author">{author}</span>
  <p class="message-bubble__content">{content}</p>
  <time class="message-bubble__timestamp">{timestamp}</time>
</div>

// packages/ui/output/react/src/MessageBubble/MessageBubble.tsx
import * as React from "react";

export interface MessageBubbleProps {
    author?: string;
    className?: string;
    content?: string;
    isOwn?: boolean;
    timestamp?: string;
}

function MessageBubble(props: MessageBubbleProps) {
    props = {
        author: "",
        className: "",
        content: "",
        isOwn: false,
        timestamp: "",
        ...props,
    };
    return (
        <div
            className={`message-bubble ${props.isOwn ? "message-bubble--own" : ""} ${
                props.className
            }`}
        >
            <span className="message-bubble__author">{props.author}</span>
            <p className="message-bubble__content">{props.content}</p>
            <time className="message-bubble__timestamp">{props.timestamp}</time>
        </div>
    );
}

export default MessageBubble;
