// packages/ui/output/svelte/src/MessageChunk/MessageChunk.svelte
<script context="module" lang="ts">
  export interface MessageChunkProps {
    authorID: string;
    authorName?: string;
    avatarSize?: number;
    avatarSrc?: string;
    className?: string;
    isSelf?: boolean;
    messages?: string[];
    timestamp?: string;
  }
</script>

<script lang="ts">
  import Avatar from "../Avatar/Avatar.svelte";

  export let authorName: MessageChunkProps["authorName"] = undefined;
  export let authorID: MessageChunkProps["authorID"] = "";
  export let className: MessageChunkProps["className"] = "";
  export let avatarSize: MessageChunkProps["avatarSize"] = 36;
  export let avatarSrc: MessageChunkProps["avatarSrc"] = undefined;
  export let isSelf: MessageChunkProps["isSelf"] = false;
  export let timestamp: MessageChunkProps["timestamp"] = "";
  export let messages: MessageChunkProps["messages"] = [];
  function stringifyStyles(stylesObj) {
    let styles = "";
    for (let key in stylesObj) {
      const dashedKey = key.replace(/[A-Z]/g, function (match) {
        return "-" + match.toLowerCase();
      });
      styles += dashedKey + ":" + stylesObj[key] + ";";
    }
    return styles;
  }

  $: displayName = () => {
    return authorName || (authorID ? authorID.slice(0, 8) : "");
  };
</script>

<div
  style={stringifyStyles({
    display: "flex",
    gap: "10px",
    padding: "4px 0",
  })}
  class={`message-chunk ${className}`}
>
  <Avatar
    displayName={authorName}
    size={avatarSize}
    src={avatarSrc}
    userID={authorID}
  />
  <div
    style={stringifyStyles({
      flex: "1",
      minWidth: "0",
    })}
    class="message-chunk__body"
  >
    <div
      style={stringifyStyles({
        alignItems: "baseline",
        display: "flex",
        gap: "8px",
        marginBottom: "2px",
      })}
      class="message-chunk__header"
    >
      <span
        style={stringifyStyles({
          fontSize: "14px",
          fontWeight: "600",
        })}
        class={`message-chunk__author ${
          isSelf ? "message-chunk__author--self" : ""
        }`}>{displayName()}</span
      ><time
        style={stringifyStyles({
          fontSize: "11px",
          opacity: "0.5",
        })}
        class="message-chunk__time">{timestamp}</time
      >
    </div>
    {#each messages as message}
      <div
        style={stringifyStyles({
          fontSize: "14px",
          lineHeight: "1.5",
          paddingTop: "1px",
          wordBreak: "break-word",
        })}
        class="message-chunk__line"
      >
        {@html message}
      </div>
    {/each}
  </div>
</div>

// packages/ui/output/react/src/MessageChunk/MessageChunk.tsx
import * as React from "react";

export interface MessageChunkProps {
  authorID: string;
  authorName?: string;
  avatarSrc?: string;
  timestamp?: string;
  messages?: string[];
  isSelf?: boolean;
  avatarSize?: number;
  className?: string;
}

import Avatar from "../Avatar/Avatar";

function MessageChunk(props: MessageChunkProps) {
  props = {
    timestamp: "",
    messages: [],
    isSelf: false,
    avatarSize: 36,
    className: "",
    ...props,
  };
  function displayName() {
    return (
      props.authorName || (props.authorID ? props.authorID.slice(0, 8) : "")
    );
  }

  return (
    <div
      className={`message-chunk ${props.className}`}
      style={{
        display: "flex",
        gap: "10px",
        padding: "4px 0",
      }}
    >
      <Avatar
        userID={props.authorID}
        src={props.avatarSrc}
        size={props.avatarSize}
        displayName={props.authorName}
      />
      <div
        className="message-chunk__body"
        style={{
          flex: "1",
          minWidth: "0",
        }}
      >
        <div
          className="message-chunk__header"
          style={{
            display: "flex",
            alignItems: "baseline",
            gap: "8px",
            marginBottom: "2px",
          }}
        >
          <span
            className={`message-chunk__author ${
              props.isSelf ? "message-chunk__author--self" : ""
            }`}
            style={{
              fontWeight: "600",
              fontSize: "14px",
            }}
          >
            {displayName()}
          </span>
          <time
            className="message-chunk__time"
            style={{
              fontSize: "11px",
              opacity: "0.5",
            }}
          >
            {props.timestamp}
          </time>
        </div>
        {props.messages?.map((message) => (
          <div
            className="message-chunk__line"
            dangerouslySetInnerHTML={{ __html: message }}
            style={{
              fontSize: "14px",
              lineHeight: "1.5",
              paddingTop: "1px",
              wordBreak: "break-word",
            }}
          />
        ))}
      </div>
    </div>
  );
}

export default MessageChunk;
