// packages/ui/output/svelte/src/Badge/Badge.svelte
<script context="module" lang="ts">
  export interface BadgeProps {
    variant?: "online" | "offline" | "dnd" | "idle";
    label?: string;
    className?: string;
  }
</script>

<script lang="ts">
  export let variant: BadgeProps["variant"] = "offline";
  export let className: BadgeProps["className"] = "";
  export let label: BadgeProps["label"] = "";
</script>

<span
  class={`badge badge--${variant} ${className}`}
  aria-label={label}
  title={label}
/>

// packages/ui/output/react/src/Badge/Badge.tsx
import * as React from "react";

export interface BadgeProps {
    className?: string;
    label?: string;
    variant?: "dnd" | "idle" | "offline" | "online";
}

function Badge(props: BadgeProps) {
    props = { className: "", label: "", variant: "offline", ...props };
    return (
        <span
            aria-label={props.label}
            className={`badge badge--${props.variant} ${props.className}`}
            title={props.label}
        />
    );
}

export default Badge;
