// packages/ui/output/react/src/StatusDot/StatusDot.tsx
import * as React from "react";

export interface StatusDotProps {
    className?: string;
    status?: StatusDotStatus;
}
export type StatusDotStatus = "away" | "dnd" | "offline" | "online";

function StatusDot(props: StatusDotProps) {
    props = { className: "", status: "offline", ...props };
    function color() {
        if (props.status === "online") return "#43a047";
        if (props.status === "away") return "#fb8c00";
        if (props.status === "dnd") return "#e53935";
        return "#666666";
    }

    return (
        <span
            aria-label={props.status}
            className={`status-dot ${props.className}`}
            style={{
                backgroundColor: color(),
                borderRadius: "50%",
                display: "inline-block",
                flexShrink: "0",
                height: "8px",
                width: "8px",
            }}
        />
    );
}

export default StatusDot;

// packages/ui/output/svelte/src/StatusDot/StatusDot.svelte
<script context="module" lang="ts">
  export interface StatusDotProps {
    className?: string;
    status?: StatusDotStatus;
  }

  export type StatusDotStatus = "away" | "dnd" | "offline" | "online";
</script>

<script lang="ts">
  export let status: StatusDotProps["status"] = "offline";
  export let className: StatusDotProps["className"] = "";
  function stringifyStyles(stylesObj) {
    let styles = "";
    for (let key in stylesObj) {
      const dashedKey = key.replace(/[A-Z]/g, function (match) {
        return "-" + match.toLowerCase();
      });
      styles += dashedKey + ":" + stylesObj[key] + ";";
    }
    return styles;
  }

  $: color = () => {
    if (status === "online") return "#43a047";
    if (status === "away") return "#fb8c00";
    if (status === "dnd") return "#e53935";
    return "#666666";
  };
</script>

<span
  style={stringifyStyles({
    backgroundColor: color(),
    borderRadius: "50%",
    display: "inline-block",
    flexShrink: "0",
    height: "8px",
    width: "8px",
  })}
  aria-label={status}
  class={`status-dot ${className}`}
/>
