// packages/ui/output/react/src/Modal/Modal.tsx
"use client";
import * as React from "react";

export interface ModalProps {
  isOpen?: boolean;
  title?: string;
  className?: string;
  onClose?: () => void;
  children?: any;
}

function Modal(props: ModalProps) {
  props = { isOpen: false, title: "", className: "", ...props };
  return (
    <>
      {props.isOpen ? (
        <>
          <div
            className="modal-backdrop"
            onClick={(event) => props.onClose?.()}
          >
            <div
              className={`modal ${props.className}`}
              onClick={(e) => e.stopPropagation()}
            >
              <div className="modal__header">
                <span className="modal__title">{props.title}</span>
                <button
                  className="modal__close"
                  type="button"
                  aria-label="Close"
                  onClick={(event) => props.onClose?.()}
                >
                  ✕
                </button>
              </div>
              <div className="modal__body">{props.children}</div>
            </div>
          </div>
        </>
      ) : null}
    </>
  );
}

export default Modal;

// packages/ui/output/svelte/src/Modal/Modal.svelte
<script context="module" lang="ts">
  export interface ModalProps {
    isOpen?: boolean;
    title?: string;
    className?: string;
    onClose?: () => void;
    children?: any;
  }
</script>

<script lang="ts">
  export let isOpen: ModalProps["isOpen"] = false;
  export let onClose: ModalProps["onClose"] = undefined;
  export let className: ModalProps["className"] = "";
  export let title: ModalProps["title"] = "";
</script>

{#if isOpen}
  <div
    class="modal-backdrop"
    on:click={(event) => {
      onClose?.();
    }}
  >
    <div
      class={`modal ${className}`}
      on:click={(e) => {
        e.stopPropagation();
      }}
    >
      <div class="modal__header">
        <span class="modal__title">{title}</span><button
          class="modal__close"
          type="button"
          aria-label="Close"
          on:click={(event) => {
            onClose?.();
          }}
        >
          ✕
        </button>
      </div>
      <div class="modal__body"><slot /></div>
    </div>
  </div>
{/if}
