// packages/ui/output/react/src/SearchBar/SearchBar.tsx
"use client";
import * as React from "react";

export interface SearchBarProps {
  value?: string;
  placeholder?: string;
  className?: string;
  onInput?: (value: string) => void;
}

function SearchBar(props: SearchBarProps) {
  props = { value: "", placeholder: "Search...", className: "", ...props };
  return (
    <div className={`search-bar ${props.className}`}>
      <span className="search-bar__icon" aria-hidden="true">
        🔍
      </span>
      <input
        className="search-bar__input"
        type="search"
        value={props.value}
        placeholder={props.placeholder}
        onInput={(e) => props.onInput?.(e.target.value)}
      />
    </div>
  );
}

export default SearchBar;

// packages/ui/output/svelte/src/SearchBar/SearchBar.svelte
<script context="module" lang="ts">
  export interface SearchBarProps {
    value?: string;
    placeholder?: string;
    className?: string;
    onInput?: (value: string) => void;
  }
</script>

<script lang="ts">
  export let className: SearchBarProps["className"] = "";
  export let value: SearchBarProps["value"] = "";
  export let placeholder: SearchBarProps["placeholder"] = "Search...";
  export let onInput: SearchBarProps["onInput"] = undefined;
</script>

<div class={`search-bar ${className}`}>
  <span class="search-bar__icon" aria-hidden="true"> 🔍 </span><input
    class="search-bar__input"
    type="search"
    {value}
    {placeholder}
    on:input={(e) => {
      onInput?.(e.target.value);
    }}
  />
</div>
